/**
 * MyPI Commands Extension
 *
 * Custom slash commands for persona management and shell integration.
 *
 * Commands:
 *   /make <name>    - Create a new persona: directory, MyPi repo, shell alias
 *   /init           - Initialize persona: scout review + create AGENTS.md
 *   /personas       - List all available personas
 */

import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";
import { writeFileSync, appendFileSync, existsSync, mkdirSync, readdirSync, readFileSync } from "fs";
import { join } from "path";
import { homedir } from "os";
import { spawn } from "child_process";

async function runCommand(cmd: string, args: string[], cwd?: string): Promise<{ exitCode: number; stdout: string; stderr: string }> {
  return new Promise((resolve) => {
    const proc = spawn(cmd, args, { shell: true, cwd });
    let stdout = "";
    let stderr = "";

    proc.stdout?.on("data", (chunk) => { stdout += chunk; });
    proc.stderr?.on("data", (chunk) => { stderr += chunk; });

    proc.on("close", (code) => {
      resolve({ exitCode: code ?? 1, stdout, stderr });
    });

    proc.on("error", (err) => {
      resolve({ exitCode: 1, stdout: "", stderr: err.message });
    });
  });
}

interface ScoutFindings {
  stack: string;
  structure: string;
  domain: string;
  config: string;
}

function parseScoutOutput(output: string): ScoutFindings {
  const lines = output.split("\n");
  const findings: ScoutFindings = {
    stack: "Unknown",
    structure: "Unknown",
    domain: "Unknown",
    config: "None found",
  };

  for (const line of lines) {
    if (line.startsWith("Stack:")) findings.stack = line.replace("Stack:", "").trim();
    else if (line.startsWith("Structure:")) findings.structure = line.replace("Structure:", "").trim();
    else if (line.startsWith("Domain:")) findings.domain = line.replace("Domain:", "").trim();
    else if (line.startsWith("Config:")) findings.config = line.replace("Config:", "").trim();
  }

  return findings;
}

function generateAgentsMd(findings: ScoutFindings, cwd: string): string {
  const projectName = cwd.split("/").pop() || "this project";
  const date = new Date().toISOString().split("T")[0];

  return `# ${projectName} - Agent Context

## Project

**Name:** ${projectName}
**Scouted:** ${date}

## Stack

${findings.stack}

## Structure

${findings.structure}

## Domain

${findings.domain}

## Agent Configuration

${findings.config}

## Guidelines

- Be thorough and document your work
- Write complete, working code
- Leave the codebase better than you found it
- When uncertain, ask before acting on external actions

## Notes

This AGENTS.md was auto-generated by \`/init\` from scout analysis.
Update manually as the project evolves.
`;
}

// ─────────────────────────────────────────────────────────────
// Helper: Run pi as subagent for analysis
// ─────────────────────────────────────────────────────────────

async function runPiSubagent(prompt: string, model: string, cwd: string): Promise<{ exitCode: number; stdout: string; stderr: string }> {
  return new Promise((resolve) => {
    const args = [
      "--mode", "json",
      "-p",
      "--no-extensions",
      "--model", model,
      "--thinking", "off",
      "--session", "/dev/null",
    ];

    const proc = spawn("pi", args, {
      cwd,
      stdio: ["pipe", "pipe", "pipe"],
      shell: true,
    });

    let stdout = "";
    let stderr = "";
    let buffer = "";

    proc.stdout?.on("data", (chunk) => {
      buffer += chunk;
      const lines = buffer.split("\n");
      buffer = lines.pop() || "";
      for (const line of lines) {
        if (!line.trim()) continue;
        try {
          const event = JSON.parse(line);
          if (event.type === "message_update") {
            const delta = event.assistantMessageEvent;
            if (delta?.type === "text_delta") {
              stdout += delta.delta || "";
            }
          }
        } catch {
          // Accumulate non-JSON lines as stdout
          stdout += line + "\n";
        }
      }
    });

    proc.stderr?.on("data", (chunk) => { stderr += chunk; });

    proc.on("close", (code) => {
      resolve({ exitCode: code ?? 0, stdout, stderr });
    });

    proc.on("error", (err) => {
      resolve({ exitCode: 1, stdout: "", stderr: err.message });
    });

    // Send the prompt
    proc.stdin?.write(prompt + "\n");
    proc.stdin?.end();
  });
}

// ─────────────────────────────────────────────────────────────
// Extension
// ─────────────────────────────────────────────────────────────

export default function (pi: ExtensionAPI) {

  // ── /make <name> ──────────────────────────────────────────

  pi.registerCommand("make", {
    description: "Create a new persona: directory, MyPi repo, shell alias",

    async handler(args: string, ctx: any): Promise<void> {
      const name = args.trim();

      if (!name) {
        ctx.ui.notify("Usage: /make <name>\nCreates a new persona with MyPi repo and shell alias.", "warning");
        return;
      }

      if (!/^[a-zA-Z0-9_-]+$/.test(name)) {
        ctx.ui.notify(`Invalid name "${name}". Use only letters, numbers, dash, underscore.`, "error");
        return;
      }

      const home = homedir();
      const personasDir = join(home, ".pi", "personas");
      const personaDir = join(personasDir, name);
      const mypiUrl = "https://github.com/Nuosis/MyPi.git";

      if (existsSync(personaDir)) {
        ctx.ui.notify(`Directory ~/.pi/personas/${name} already exists.`, "warning");
        return;
      }

      ctx.ui.setStatus("mypi-commands", `Creating persona: ${name}`);

      // Create directory
      try {
        mkdirSync(personasDir, { recursive: true });
        mkdirSync(personaDir, { recursive: true });
      } catch (err) {
        ctx.ui.notify(`Failed to create directory: ${err}`, "error");
        return;
      }

      // Git clone MyPi
      ctx.ui.notify(`Cloning MyPi into ~/.pi/personas/${name}...`, "info");
      const cloneResult = await runCommand("git", ["clone", mypiUrl, personaDir]);

      if (cloneResult.exitCode !== 0) {
        ctx.ui.notify(`Git clone failed: ${cloneResult.stderr}`, "error");
        return;
      }

      // Install dependencies in agent directory
      const agentDir = join(personaDir, "agent");
      ctx.ui.notify(`Installing dependencies...`, "info");
      const installResult = await runCommand("npm", ["install"], agentDir);

      if (installResult.exitCode !== 0) {
        ctx.ui.notify(`npm install failed: ${installResult.stderr}`, "warning");
      }

      // Overwrite settings.json with persona-specific config using relative paths
      // This ensures extensions are resolved relative to the persona's agent dir
      const settingsPath = join(agentDir, "settings.json");
      const personaSettings = {
        lastChangelogVersion: "0.70.2",
        defaultProvider: "minimax",
        defaultModel: "MiniMax-M2.7",
        defaultThinkingLevel: "medium",
        extensions: [
          "./extensions/mypi-commands",
          "./extensions/mypi-evals",
          "./extensions/find-guard",
          "./extensions/task-mode",
          "./extensions/subagent",
        ]
      };
      writeFileSync(settingsPath, JSON.stringify(personaSettings, null, 2), "utf-8");
      ctx.ui.notify(`Configured persona extensions`, "info");

      // Create shell function using PI_CODING_AGENT_DIR environment variable
      // Functions work better than aliases for env var + command combos
      const shellFunc = `pi-${name}() { PI_CODING_AGENT_DIR="\$HOME/.pi/personas/${name}/agent" pi "\$@"; }`;
      const shellRC = join(home, ".zshrc");

      try {
        const rcContent = existsSync(shellRC) ? readFileSync(shellRC, "utf-8") : "";
        if (!rcContent.includes(`pi-${name}`)) {
          appendFileSync(shellRC, `\n# Persona: ${name}\n${shellFunc}\n`);
          ctx.ui.notify(`Added shell function to ~/.zshrc`, "info");
        }
      } catch {
        // Ignore
      }

      ctx.ui.setStatus("mypi-commands", null);

      // Show prominent completion alert
      ctx.ui.setWidget("make-complete", (_tui: any, theme: any) => ({
        render(width: number): string[] {
          const lines = [
            "",
            theme.fg("accent", " ╔══════════════════════════════════════════╗"),
            theme.fg("accent", " ║") + "  " + theme.fg("success", theme.bold("✓ Persona Created!")) + "                              " + theme.fg("accent", "║"),
            theme.fg("accent", " ╠══════════════════════════════════════════╣"),
            theme.fg("accent", " ║") + "  " + theme.fg("muted", `Name:    `) + theme.fg("accent", name) + "                                 " + theme.fg("accent", "║"),
            theme.fg("accent", " ║") + "  " + theme.fg("muted", `Path:    `) + theme.fg("accent", `~/.pi/personas/${name}/`) + "                           " + theme.fg("accent", "║"),
            theme.fg("accent", " ║") + "  " + theme.fg("muted", `Alias:   `) + theme.fg("accent", `PI_CODING_AGENT_DIR=... pi`) + "                   " + theme.fg("accent", "║"),
            theme.fg("accent", " ╠══════════════════════════════════════════╣"),
            theme.fg("accent", " ║") + "  " + theme.fg("dim", "Next: source ~/.zshrc && PI_CODING_AGENT_DIR=~/.pi/personas/" + name + "/agent pi") + "   " + theme.fg("accent", "║"),
            theme.fg("accent", " ╚══════════════════════════════════════════╝"),
            "",
          ];
          return lines;
        },
        invalidate() {},
      }));

      // Auto-dismiss the widget after 3 seconds
      setTimeout(() => {
        ctx.ui.setWidget("make-complete", undefined);
      }, 3000);
    },
  });

  // ── /init ─────────────────────────────────────────────────

  pi.registerCommand("init", {
    description: "Initialize persona: scout review + create AGENTS.md",

    async handler(_args: string, ctx: any): Promise<void> {
      const cwd = ctx.cwd || process.cwd();
      const agentDir = join(cwd, "pi", "agent");
      const agentsMdPath = join(agentDir, "AGENTS.md");

      if (existsSync(agentsMdPath)) {
        ctx.ui.notify("AGENTS.md already exists. Delete it first to re-initialize.", "warning");
        return;
      }

      ctx.ui.setStatus("mypi-commands", "Scouting codebase...");
      ctx.ui.notify("Scouting codebase for project context...", "info");

      // Scout the codebase via subagent
      const scoutPrompt = `You are a scout. Analyze this codebase at ${cwd} and return structured findings.

Be concise, 10-15 lines max:

\`\`\`
Stack: language, framework, key deps
Structure: main directories, entry points
Domain: what this project does
Config: any existing .claude, .cursorrules, .github/copilot, etc.
\`\`\`

Start now.`;

      const result = await runPiSubagent(scoutPrompt, "MiniMax-M2.7", cwd);

      if (result.exitCode !== 0) {
        ctx.ui.notify(`Scout failed: ${result.stderr}`, "error");
        return;
      }

      const findings = parseScoutOutput(result.stdout);
      const agentsMd = generateAgentsMd(findings, cwd);

      try {
        mkdirSync(agentDir, { recursive: true });
        writeFileSync(agentsMdPath, agentsMd, "utf-8");
      } catch (err) {
        ctx.ui.notify(`Failed to write AGENTS.md: ${err}`, "error");
        return;
      }

      ctx.ui.setStatus("mypi-commands", null);
      ctx.ui.notify(
        `Initialized!\n\n` +
        `Scouted: ${findings.stack}\n` +
        `Domain: ${findings.domain}\n` +
        `Created: pi/agent/AGENTS.md\n\n` +
        `The agent now knows about this codebase.`,
        "info"
      );
    },
  });

  // ── /tool-stop ────────────────────────────────────────────

  pi.registerCommand("tool-stop", {
    description: "Stop the active tool call, abort agent, optionally explain why",

    async handler(args: string, ctx: any): Promise<void> {
      const reason = args.trim() || "User cancelled the tool call";
      const cwd = ctx.cwd || process.cwd();

      ctx.ui.notify(`⏹️ Stopping tool... Reason: "${reason}"`, "warning");

      // Abort the agent - this will stop any running tool calls
      ctx.abort();

      // After abort, optionally send a user message explaining why
      // This gives the agent context about what happened
      setTimeout(() => {
        ctx.sendUserMessage(
          `User aborted the previous tool call. Reason: ${reason}\n\n` +
          `Please acknowledge this and wait for further instructions.`,
          { deliverAs: "followUp" }
        );
      }, 500);

      ctx.ui.setStatus("tool-stop", "Stopped");
    },
  });
  
  pi.registerCommand("personas", {
    description: "List all available personas",

    async handler(_args: string, ctx: any): Promise<void> {
      const home = homedir();
      const personasDir = join(home, ".pi", "personas");

      if (!existsSync(personasDir)) {
        ctx.ui.notify("No personas found (~/.pi/personas doesn't exist)", "info");
        return;
      }

      const entries = readdirSync(personasDir, { withFileTypes: true })
        .filter(e => e.isDirectory() && !e.name.startsWith("."))
        .map(e => `  - ${e.name}`)
        .join("\n");

      if (!entries) {
        ctx.ui.notify("No personas found", "info");
        return;
      }

      ctx.ui.notify(`Available personas:\n\n${entries}\n\nUse /make <name> to create one.`, "info");
    },
  });

  // ── Session Start: clean up widgets ──────────────────────

  pi.on("session_start", async (_event, ctx) => {
    ctx.ui.setWidget("make-complete", undefined);
  });
}
